# Generated by Django 4.2 on 2026-04-01 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 1, 0, 36, 16, 438939, tzinfo=datetime.timezone.utc)),
        ),
    ]
