# Generated by Django 4.2 on 2026-04-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedstatement',
            name='statement_type',
            field=models.CharField(choices=[('is', 'Income Statement'), ('bs', 'Balance Sheet'), ('cfs', 'Cash Flow Statement'), ('ratio', 'Financial Ratios'), ('debt', 'Debt Schedule'), ('valuation', 'Valuation Metrics'), ('revenue', 'Revenue & Receivables Schedule'), ('opex', 'OpEx & Payables Schedule'), ('fixed_assets', 'Fixed Assets & Depreciation'), ('tax', 'Tax & Allowances Schedule'), ('dividend', 'Reserve Accounts & Dividends')], max_length=20),
        ),
    ]
