# Generated by Django 4.2 on 2026-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_calculatedstatement_statement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='industry_custom_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='industry_library_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='industry_library_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='industry_library_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='industry_sub_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='calculatedstatement',
            name='statement_type',
            field=models.CharField(choices=[('is', 'Income Statement'), ('bs', 'Balance Sheet'), ('cfs', 'Cash Flow Statement'), ('ratio', 'Financial Ratios'), ('debt', 'Debt Schedule'), ('valuation', 'Valuation Metrics'), ('revenue', 'Revenue & Receivables Schedule'), ('opex', 'OpEx & Payables Schedule'), ('fixed_assets', 'Fixed Assets & Depreciation'), ('tax', 'Tax & Allowances Schedule'), ('dividend', 'Reserve Accounts & Dividends'), ('exit', 'Exit & Terminal Value')], max_length=20),
        ),
    ]
