# Generated by Django 4.2 on 2026-02-23 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('report_type', models.CharField(default='Summary', max_length=100)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('report', models.FileField(blank=True, max_length=250, null=True, upload_to='reports/')),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('financial_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='model.financialmodel')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='model.scenario')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'ordering': ['-date_created'],
            },
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
